aliases:
  ГОРНЫЙ БРИЗ:
    - MOUNTAIN BREEZE
  ЛАВАНДА:
    - LAVENDER
  РОЗА:
    - ROSE
  ПИОН:
    - PEONY
  ЛИМОН:
    - LEMON
  ЦВЕТОВ СВЕЖЕСТИ:
    - FLORAL MIST
  КОКОС:
    - COCONUT
  АЛОЭВЕРА:
    - ALOE VERA
  АЛОЕ ВЕРА:
    - ALOE VERA
  БЭБИ:
    - BABY
