aliases:
  Кондиционер:
    - КОНДИЦИОНЕР
  Гель для душа:
    - ГЕЛЬ ДЛЯ ДУША
  Шампунь:
    - ШАМПУН
    - SHAMP
  Жидкое мыло:
    - ЖИДКОЕ МЫЛО
  Крем-мыло:
    - КРЕМ МЫЛ
    - КРЕМ-МЫЛ
  Мыло:
    - МЫЛ
  ЖМС:
    - ЖМС
    - ЖИДКОЕ МОЮЩЕЕ
