aliases:
  ГОЛУБОЙ: []
  ФИОЛЕТОВЫЙ: []
  РОЗОВЫЙ: []
  КРАСНЫЙ: []
  ЧЕРНЫЙ: []
  ЖЕЛТЫЙ: []
  ЗЕЛЕНЫЙ: []
  СИНИЙ: []
  WHITE: []
  BLACK: []
  BLUE: []
  GREEN: []
  YELLOW: []
  RED: []
  PINK: []
  PURPLE: []
