words:
  - ПАРФЮМИРОВАННЫЙ
  - ПАРФЮМИРОВАННАЯ
  - ПАРФЮМИРОВАННОЕ
  - ПАРФЮМ
  - С АРОМАТОМ
  - АРОМАТ
  - ДЛЯ СТИРКИ
  - ДЕТСКИХ ВЕЩЕЙ
  - ДЛЯ ВОЛОС
  - ЖИДКОЕ
  - МОЮЩЕЕ
  - СРЕДСТВО

title_case_lower_words:
  - для
  - с
  - и
  - в
  - на
  - по
  - de
  - of
